[deploy]
bucket = 'cfn-artifacts-realmanny'
region = 'us-east-1'
stack_name = 'CrdCicd'

[parameters]
ServiceStack = 'CrdSrvBackendFlask'
ClusterStack = 'CrdCluster'
GitHubBranch = 'prod'
GithubRepo = 'AWS-bootcamp'
ArtifactBucketName = "codepipeline-cruddur-artifacts-realmanny"