#! /usr/bin/env bash
set -e # stop the execution of the script if it fails

ARTIFACT_BUCKET="cfn-artifacts-realmanny"
TEMPLATE_PATH="/workspace/AWS-bootcamp/.aws-sam/build/template.yaml"
OUTPUT_TEMPLATE_PATH="/workspace/AWS-bootcamp/.aws-sam/build/packaged.yaml"
CONFIG_PATH="/workspace/AWS-bootcamp/ddb/config.toml"

echo "== package"
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-package.html
sam package \
  --s3-bucket $ARTIFACT_BUCKET \
  --config-file $CONFIG_PATH \
  --output-template-file $OUTPUT_TEMPLATE_PATH \
  --template-file $TEMPLATE_PATH \
  --s3-prefix "ddb"