[deploy]
bucket = 'cfn-artifacts-realmanny'
region = 'us-east-1'
stack_name = 'CrdFrontend'

[parameters]
CertificateArn = 'arn:aws:acm:us-east-1:523227374974:certificate/5fe85613-5abc-4d46-a6e7-b9b23cdc9137'
WwwBucketName = 'www.realmanny.tech'
RootBucketName = 'realmanny.tech'